In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [6]:
# Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue. Remember
#that there's a different cost for guests and members! */

In [8]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, revenue from(
        SELECT f.name, SUM(CASE
        WHEN memid = 0 then slots * f.guestcost
        ELSE slots*f.membercost
        END) AS revenue
        FROM Bookings AS b
        INNER JOIN Facilities AS f
        ON b.facid = f.facid
        GROUP BY f.name
        ) AS agg
        WHERE revenue < 1000
        ORDER BY revenue;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [ ]:
Check the result

In [13]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT firstname ||' '|| surname AS member_name,
        (SELECT firstname  ||' '|| surname AS recommendedby
        FROM Members
        Where memid = recommendedby
        )
        FROM Members
        Order by member_name;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Anna Mackenzie', None)
('Anne Baker', None)
('Burton Tracy', None)
('Charles Owen', None)
('Darren Smith', None)
('Darren Smith', None)
('David Farrell', None)
('David Jones', None)
('David Pinker', None)
('Douglas Jones', None)
('Erica Crumpet', None)
('Florence Bader', None)
('GUEST GUEST', None)
('Gerald Butters', None)
('Henrietta Rumney', None)
('Henry Worthington-Smyth', None)
('Hyacinth Tupperware', None)
('Jack Smith', None)
('Janice Joplette', None)
('Jemima Farrell', None)
('Joan Coplin', None)
('John Hunt', None)
('Matthew Genting', None)
('Millicent Purview', None)
('Nancy Dare', None)
('Ponder Stibbons', None)
('Ramnaresh Sarwin', None)
('Tim Boothe', None)
('Tim Rownam', None)
('Timothy Baker', None)
('Tracy Smith', None)

Q12: Find the facilities with their usage by member, but not guests

Please check this result too.

In [22]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT b.facid, f.name, SUM(b.slots) AS total_slots
        FROM Bookings AS b
        INNER JOIN Facilities AS f
        ON b.facid = f.facid
        GROUP BY b.facid
        ORDER BY b.facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 1320)
(1, 'Tennis Court 2', 1278)
(2, 'Badminton Court', 1209)
(3, 'Table Tennis', 830)
(4, 'Massage Room 1', 1404)
(5, 'Massage Room 2', 228)
(6, 'Squash Court', 1104)
(7, 'Snooker Table', 908)
(8, 'Pool Table', 910)

Q13: Find the facilities usage by month, but not guests

In [ ]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, revenue from(
        SELECT f.name, SUM(CASE
        WHEN memid = 0 then slots * f.guestcost
        ELSE slots*f.membercost
        END) AS revenue
        FROM Bookings AS b
        INNER JOIN Facilities AS f
        ON b.facid = f.facid
        GROUP BY f.name
        ) AS agg
        WHERE revenue < 1000
        ORDER BY revenue;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()